load("//:copts.bzl", "RSR_DEFAULT_COPTS")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "bench",
    srcs = ["rmls_bench.cxx"],
    hdrs = ["rmls_bench.hxx"],
    copts = RSR_DEFAULT_COPTS,
    )
