cxx_library(
    name='irect',
    srcs=['rmlg_irect.cxx'],
    hdrs=['rmlg_irect.hxx'],
    deps=[
        'src/rml/rmlv:vec',
        ],
    )

cxx_library(
    name='triangle',
    srcs=['rmlg_triangle.cxx'],
    hdrs=['rmlg_triangle.hxx'],
    deps=[
        'src/rml/rmlv:vec',
        ],
    )
